[package]
name = "containy-thing"
version = "0.1.0"
authors = ["Kamal Marhubi <kamal@marhubi.com>"]

[dependencies]
clap = "2"
env_logger = "0.3"
itertools = "0.5"
libc = "0.2"
log = "0.3"
nix = "0.5"
tempdir = "0.3"
walkdir = "0.1"
